/**
 * V2 Engine — Prompt Builder
 *
 * Standalone: exports the versioned system prompt + few-shot examples
 * that govern a single V2 LLM call (intent classification + natural reply
 * in one JSON payload — Part 1 Design Decision).
 *
 * No wiring to interpreter.ts / reasoning.ts / fallback.service.ts.
 *
 * Implements Part 5 of CHAT-ENGINE-V2-DESIGN-P1.md (final version after
 * P1-FIX + P1-FIX-2), including 5 few-shot examples — 5th being the
 * variant-confirmation case (rule 13). P1-FIX-3 added rule 13 + 14.
 *
 * CHANGES (FIX-PROMPT-DOMAIN-AND-CATALOG-SCALING):
 *   - System prompt translated to English (domain-neutral: "chat commerce").
 *   - Shot 2 (hardcoded "wartel") removed — replaced by dynamic template
 *     buildDynamicRemoveShot() that injects a REAL product name from the
 *     store catalog at prompt-build time.
 *   - buildV2Prompt() now accepts optional businessCategory + catalogItems
 *     for context injection. If no catalog available, a generic placeholder
 *     product name is used (never food-specific, never hardcode).
 *
 * CHANGES (TRIM-ENGLISH-SYSTEM-PROMPT):
 *   - System prompt trimmed by ~24% (5,602 → 4,281 chars) by consolidating
 *     redundant rules. Rules 1+2 merged, Rule 12 merged into Rule 3,
 *     verbose examples removed, schema compacted.
 *   - Substantive rules preserved: Rule 13 (variant confirmation) and
 *     Rule 14 (intent/action consistency) remain unchanged.
 *   - Version: v1.1.0 → v1.2.0
 *
 * The system prompt is a single importable constant so it can be diff'd
 * when the prompt content changes. Version is bumped in
 * `V2_ENGINE_PROMPT_VERSION` whenever the text below is edited.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Versioned constants
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Bump this whenever the system-prompt text changes (new rules, revised
 * examples, adjusted tone). Consumers that cache by version will rebuild
 * their prompt automatically.
 *
 * v1.2.1: Added Rule 12 (payment method disclosure) + SHOW_PAYMENT_METHODS
 * action_type. When the customer asks to pay / wants payment methods
 * (transfer, QRIS, COD), the LLM now emits intent 'payment_inquiry' with a
 * SHOW_PAYMENT_METHODS proposed_action. The v2-rewrite active path maps this
 * back to the proven V1 payment trigger (source=PAYMENT + qrisImageUrl) so the
 * WA gateway sends the QRIS image / bank account info / COD confirmation.
 *
 * v1.2.0: Trimmed English system prompt by ~24% (redundant rules merged,
 * verbose examples removed, schema compacted). Substantive rules (13/14)
 * preserved unchanged. No katalog overhead (only ~26 tokens for 3 products).
 */
export const V2_ENGINE_PROMPT_VERSION = 'v1.2.1';

/** JSON schema version the LLM is instructed to emit (mirrors V2_SCHEMA_VERSION). */
export const V2_ENGINE_SCHEMA_VERSION = 'v1';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────

/** Single few-shot example: user message + expected JSON output. */
export interface V2FewShot {
  user_message: string;
  expected_json: string;
}

/** Options for buildV2Prompt — contextual injection of store identity + catalog. */
export interface BuildV2PromptOptions {
  /** Store business category (e.g. "Spare Parts") — injected as 1 contextual sentence. */
  businessCategory?: string | null;
  /** Pre-filtered catalog items — used for dynamic few-shot Shot 2 + catalog layer. */
  catalogItems?: CatalogItemForPrompt[];
}

/** Minimal catalog item shape for prompt injection (avoids coupling to setops.js). */
export interface CatalogItemForPrompt {
  id: string;
  name: string;
  price: number;
  category: string | null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Few-shot examples (STATIC — no food-specific product names)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * 4 static few-shot examples — minimal set, dialeksi edge-cases sering salah
 * (variant, remove-from-cart, total, Bengkel Didik false-cancel).
 *
 * Shot 2 (remove-from-cart) is NOT static — it is dynamically generated by
 * buildDynamicRemoveShot() using a real product name from the store catalog.
 * Di-review tiap bulan (Design §5: "not grow indefinitely").
 */
export const V2_ENGINE_FEW_SHOTS: V2FewShot[] = [
  // ── Shot 1 — Add to cart with variant ──────────────────────────────────
  {
    user_message: 'Saya mau beli sepatu warna merah size L',
    expected_json: `{
  "schema_version": "v1",
  "intent": "add_to_cart",
  "confidence": 0.9,
  "entities": [
    {"type": "product", "value": "sepatu", "confidence": 0.95},
    {"type": "variant", "value": "merah size L", "confidence": 0.9, "metadata": {"variant": "merah size L"}}
  ],
  "proposed_actions": [
    {"action_type": "ADD_TO_CART", "payload": {"product": "sepatu", "variant": "merah size L", "qty": 1}, "confidence": 0.9, "requires_validation": true}
  ],
  "reply_text": "Oke, sepatu warna merah size L sudah ditambahkan ke keranjang! Mau lanjut belanja atau checkout sekarang?",
  "needs_clarification": false,
  "summary_update": "Customer menambahkan sepatu merah size L ke keranjang."
}`,
  },

  // ── Shot 2 — Remove item from cart (modify_cart) ────────────────────────
  // NOTE: This shot is now DYNAMIC. Built by buildDynamicRemoveShot() using
  // a real product name from the store catalog. See buildV2Prompt().
  {
    user_message: '__DYNAMIC__',
    expected_json: '__DYNAMIC__',
  },

  // ── Shot 3 — Ask total (done_ordering) ──────────────────────────────────
  {
    user_message: 'Totalnya berapa?',
    expected_json: `{
  "schema_version": "v1",
  "intent": "done_ordering",
  "confidence": 0.85,
  "entities": [],
  "proposed_actions": [
    {"action_type": "OPEN_CART", "payload": {}, "confidence": 0.85, "requires_validation": false}
  ],
  "reply_text": "Ini rekap keranjang Kakak ya —",
  "needs_clarification": false,
  "summary_update": "Customer siap checkout, minta total."
}`,
  },

  // ── Shot 4 — False-cancel prevention: "ga jadi" for one item ≠ cancel entire order ───────────────────
  // "ga jadi" untuk satu item = REMOVE_FROM_CART (modify_cart), BUKAN
  // cancel_order. Customer masih ingin lanjut dengan item lain — jangan
  // pernah trigger full-order cancellation dari pola "ga jadi <satu item>".
  // Bengkel Didik transcript: false-cancel lebih merusak kepercayaan daripada
  // "maaf, coba lagi" (Design §4 Emergency Fallback).
  {
    user_message: 'Eh, ban dalam ga jadi deh, tinggal ban depan aja',
    expected_json: `{
  "schema_version": "v1",
  "intent": "modify_cart",
  "confidence": 0.9,
  "entities": [
    {"type": "product", "value": "ban dalam", "confidence": 0.95},
    {"type": "product", "value": "ban depan", "confidence": 0.9}
  ],
  "proposed_actions": [
    {"action_type": "REMOVE_FROM_CART", "payload": {"product": "ban dalam"}, "confidence": 0.95, "requires_validation": true}
  ],
  "reply_text": "Oke, ban dalam sudah dihapus dari keranjang. Tinggal ban depan ya, mau lanjut checkout?",
  "needs_clarification": false,
  "summary_update": "Customer hapus ban dalam dari keranjang, tinggal ban depan."
}`,
  },

  // ── Shot 5 — Variant confirmation (Rule 13) ─────────────────────────────
  // Customer sebutkan produk + variant di turn sebelumnya, lalu konfirmasi
  // pendek ("ya") → langsung ADD_TO_CART, JANGAN tanya ulang.
  {
    user_message: 'Ban dalam motor ukuran 100/90-17, ya tambahkan ke keranjang.',
    expected_json: `{
  "schema_version": "v1",
  "intent": "add_to_cart",
  "confidence": 0.95,
  "entities": [
    {"type": "product", "value": "ban dalam motor", "confidence": 0.95},
    {"type": "variant", "value": "100/90-17", "confidence": 0.95, "metadata": {"variant": "100/90-17"}}
  ],
  "proposed_actions": [
    {"action_type": "ADD_TO_CART", "payload": {"product": "ban dalam motor", "variant": "100/90-17", "qty": 1}, "confidence": 0.95, "requires_validation": true}
  ],
  "reply_text": "Siap, ban dalam motor ukuran 100/90-17 sudah dimasukkan ke keranjang ya! Mau lanjut belanja atau checkout sekarang?",
  "needs_clarification": false,
  "summary_update": "Customer mengonfirmasi penambahan ban dalam motor ukuran 100/90-17 ke keranjang."
}`,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// Dynamic Shot 2 builder — replaces hardcoded "wartel" with real catalog product
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Generate Shot 2 (remove-from-cart) using a real product name from the
 * store catalog. If no catalog items are available, falls back to a
 * generic placeholder ("produk ini") — NEVER food-specific.
 */
export function buildDynamicRemoveShot(catalogItems?: CatalogItemForPrompt[]): string {
  const productName = (catalogItems && catalogItems.length > 0)
    ? catalogItems[0].name
    : 'produk ini';

  const escapedProduct = productName.replace(/"/g, '');

  return `{
  "schema_version": "v1",
  "intent": "modify_cart",
  "confidence": 0.95,
  "entities": [
    {"type": "product", "value": "${escapedProduct}", "confidence": 0.95}
  ],
  "proposed_actions": [
    {"action_type": "REMOVE_FROM_CART", "payload": {"product": "${escapedProduct}"}, "confidence": 0.95, "requires_validation": true}
  ],
  "reply_text": "Oke, ${escapedProduct} sudah dihapus dari keranjang. Ada yang ingin ditambahkan lagi?",
  "needs_clarification": false,
  "summary_update": "Customer membatalkan ${escapedProduct} dari keranjang."
}`;
}

// ─────────────────────────────────────────────────────────────────────────────
// System prompt (English — domain-neutral "chat commerce")
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Base system prompt (English, domain-neutral).
 *
 * The English rules + schema are the single source of truth.
 * Indonesian is retained ONLY for few-shot reply_text (customer-facing tone).
 *
 * Business context sentence + dynamic Shot 2 are injected by buildV2Prompt().
 *
 * v1.2.0: Trimmed by ~24% from v1.1.0. Redundant rules consolidated:
 *   - Rules 1+2 merged (output JSON + combined classifier-responder)
 *   - Rule 12 "no hallucinate" merged into Rule 3
 *   - Verbose examples removed from rules (kept in few-shots)
 *   - Schema compacted (uncertainty_signals removed, inline entities/actions)
 *   - Intent descriptions shortened
 *   Substantive rules 13 (variant confirmation) and 14 (intent/action
 *   consistency) preserved UNCHANGED — proven critical in shadow testing.
 */
export const V2_ENGINE_SYSTEM_PROMPT_BASE: string = `You are QloBot, a friendly AI assistant for commerce chat. You speak in Bahasa Indonesia with a casual, warm tone, like talking to a friend.

=== IMPORTANT RULES ===

1. Output ONLY valid JSON matching the schema below. Do not include text, markdown, or explanations outside JSON. You are a combined classifier + responder in ONE step — classify intent AND provide reply_text simultaneously. reply_text MUST be filled for every response (1-2 sentences, casual warm Bahasa Indonesia).

2. Do NOT include prices/stock/variant IDs in reply_text — prices and stock will be enriched by the system after you propose actions. Only mention product name and qty generally.

3. Intent classification uses the KNOWN enum below. Pick the SINGLE most appropriate one. Do NOT invent new intents. Do NOT hallucinate products/prices not in the catalog — if unsure, use intent 'product_inquiry' with low confidence, or 'unknown'.

4. confidence is a 0.0-1.0 float measuring how confident you are in the intent classification.
   - >= 0.7: confident enough to execute directly
   - 0.4 - 0.69: not confident — ask for clarification
   - < 0.4: very uncertain — escalate to human

5. If the customer is confirming/answering an active clarification, fill entities from the answer. Do not create a new clarification.

6. If the customer mentions a product with its variant (color/size), save the variant description in entities[].metadata.variant. Do NOT put it in unmatched_mentions.

7. Removing one product: use intent modify_cart with action REMOVE_FROM_CART. For full order cancellation, use intent cancel_order. Example: "eh <product> ga jadi" to intent modify_cart, entities: [{type: 'product', value: '<product>'}], proposed_actions: [{action_type: REMOVE_FROM_CART, payload: {product: '<product>'}}].

8. If the user only greets (halo, sore, pagi) or does smalltalk, use intent 'smalltalk', proposed_actions=[], and provide a friendly reply_text.

9. summary_update: 1-2 sentences summarizing conversation state after this message.

10. **Variant confirmation rule**: If the conversation STATE or recent history (layers 2-3) already mentions a product + variant (e.g. "ban dalam motor 100/90-17" or "ukuran 100/90-17"), and the current user message is just a short confirmation ("ya", "oke", "boleh", "siap"), then **treat it as ADD_TO_CART** with that variant — do NOT re-ask for specifications. reply_text must include the chosen variant.

11. **Intent vs proposed_actions consistency**: If proposed_actions contains mutation actions (ADD_TO_CART, REMOVE_FROM_CART, UPDATE_CART_QUANTITY, CANCEL_ORDER) with requires_validation=true:
    - needs_clarification MUST be false
    - intent MUST be consistent with the action: ADD_TO_CART to add_to_cart, REMOVE_FROM_CART/UPDATE_CART_QUANTITY to modify_cart, CANCEL_ORDER to cancel_order
    - NEVER include mutation proposed_actions when intent is "clarification"
    - Intent "clarification" is ONLY valid when needs_clarification=true AND all proposed_actions are empty

12. **Payment method disclosure**: If the customer asks to pay or wants to know how to pay / which payment methods are available (transfer, QRIS, COD, "bayar pakai apa", "rekening berapa"), use intent 'payment_inquiry' with proposed_actions: [{action_type: SHOW_PAYMENT_METHODS, payload: {}, confidence: <0.7-0.9>, requires_validation: false}]. Do NOT invent bank account numbers or QRIS images in reply_text — the system injects the store's real, activated payment methods (transfer rekenking / QRIS image / COD) after you propose the action. reply_text should be a short friendly nudge (e.g. "Berikut metode pembayaran yang tersedia untuk Kakak ya!").

=== KNOWN INTENTS ===

- product_inquiry: Ask about products, price, availability, variants
- add_to_cart: Want to add products to cart
- done_ordering: Ready for checkout/total
- modify_cart: Change/reduce/remove items in cart
- payment_inquiry: Ask about payment methods, bank accounts, QRIS
- shipping_inquiry: Ask about shipping cost, delivery location
- order_status: Ask about order status
- cancel_order: Cancel entire order
- smalltalk: Greetings, small talk
- clarification: Answering an active clarification
- escalation: Request human/admin help
- unknown: Cannot be classified

=== OUTPUT FORMAT (JSON) ===

**CRITICAL — Use EXACTLY these type names and action_type values, do NOT invent variants:**

  entity.type: ONLY one of: product, quantity, price, variant, customer_name, customer_address, customer_phone, payment_method, shipping_method, order_status, negation, rollback, greeting, other

  action_type: ONLY one of: ADD_TO_CART, REMOVE_FROM_CART, UPDATE_CART_QUANTITY, CANCEL_ORDER, OPEN_CATALOG, OPEN_CART, SHOW_RELATED_PRODUCTS, CONTACT_ADMIN, UPDATE_SHIPPING_ADDRESS, SHOW_PAYMENT_METHODS, NONE

If the customer asks for product info → use action_type SHOW_RELATED_PRODUCTS with requires_validation=false.
If the customer wants human support → use action_type CONTACT_ADMIN with requires_validation=false.
If the customer requests to change their SHIPPING address (e.g. "ganti alamat keJl. X") → use action_type UPDATE_SHIPPING_ADDRESS with requires_validation=true and payload containing the new address.
If the customer asks to pay / wants payment methods → use intent 'payment_inquiry' with action_type SHOW_PAYMENT_METHODS (requires_validation=false); the system fills in real bank accounts / QRIS / COD.
Do NOT use variant names like name, address, location, GET_PRODUCT_INFO, ESCALATE_TO_HUMAN, etc. — map them to canonical types above.

{
  "schema_version": "v1",
  "intent": "<one of KNOWN INTENTS>",
  "confidence": 0.0-1.0,
  "entities": [{"type": "product|quantity|price|variant|customer_name|customer_address|customer_phone|payment_method|shipping_method|order_status|negation|rollback|greeting|other", "value": "<string>", "confidence": 0.0-1.0, "metadata": {}}],
  "proposed_actions": [{"action_type": "ADD_TO_CART|REMOVE_FROM_CART|UPDATE_CART_QUANTITY|CANCEL_ORDER|OPEN_CATALOG|OPEN_CART|SHOW_RELATED_PRODUCTS|CONTACT_ADMIN|UPDATE_SHIPPING_ADDRESS|NONE", "payload": {}, "confidence": 0.0-1.0, "requires_validation": true}],
  "reply_text": "<1-2 sentences, natural, Bahasa Indonesia>",
  "needs_clarification": false,
  "clarification_question": "<string or null>",
  "summary_update": "<1-2 sentences or null>"
}
`;

// ─────────────────────────────────────────────────────────────────────────────
// Prompt assembly
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Assemble the full prompt sent to the LLM: system prompt (with optional
 * business context + dynamic few-shots) + context string.
 *
 * @param context    The pre-assembled context string from buildLLMContext()
 *                   (UNIT2). Already contains STATE + HISTORY + PESAN SEKARANG.
 * @param opts       Optional contextual injection:
 *                   - businessCategory: store's business category (e.g. "Spare Parts")
 *                   - catalogItems: pre-filtered catalog for dynamic Shot 2 + catalog layer
 */
export function buildV2Prompt(context: string, opts?: BuildV2PromptOptions): string {
  const { businessCategory, catalogItems } = opts ?? {};

  // ── Business context sentence (reuse pola V1 prompt-builder.service.ts) ──
  const businessSentence = businessCategory
    ? `You are an AI assistant for a ${businessCategory} store.`
    : '';

  // ── Dynamic Shot 2 (remove-from-cart) using real catalog product ──
  const dynamicShot2 = buildDynamicRemoveShot(catalogItems);

  // ── Assemble system prompt with business context + dynamic shot ──
  const systemPrompt = `${businessSentence ? businessSentence + '\n\n' : ''}${V2_ENGINE_SYSTEM_PROMPT_BASE}

=== CONTOH (FEW-SHOT) ===

Example 1 — Add to cart with variant
Customer: "Saya mau beli sepatu warna merah size L"
${V2_ENGINE_FEW_SHOTS[0].expected_json}

Example 2 — Remove item from cart (modify_cart) [DYNAMIC — product from real catalog]
Customer: "Eh, ${catalogItems && catalogItems.length > 0 ? catalogItems[0].name : 'produk ini'} ga jadi deh"
${dynamicShot2}

Example 3 — Ask total
Customer: "Totalnya berapa?"
${V2_ENGINE_FEW_SHOTS[2].expected_json}

Example 4 — False-cancel prevention: "ga jadi" for one item ≠ cancel entire order
Customer: "Eh, ban dalam ga jadi deh, tinggal ban depan aja"
${V2_ENGINE_FEW_SHOTS[3].expected_json}

Example 5 — Variant confirmation: if variant already mentioned in prior turn, short "ya" confirmation → ADD_TO_CART (Rule 13)
Customer: "Ban dalam motor ukuran 100/90-17, ya tambahkan ke keranjang."
${V2_ENGINE_FEW_SHOTS[4].expected_json}
`;

  return `${systemPrompt}\n\n=== KONTeks ===\n${context}`;
}
