module.exports = {
  apps: [
    {
      name: 'api',
      cwd: '/home/ubuntu/garuda/apps/api',
      script: 'dist/index.js',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production', PORT: 3000, TZ: 'Asia/Jakarta' },
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 5000,
      wait_ready: true,
      wait_ready_timeout: 15000,
      max_memory_restart: '300M',
      time: true,
      error_file: '/root/.pm2/logs/garuda-api-error.log',
      out_file: '/root/.pm2/logs/garuda-api-out.log',
    },
    {
      name: 'dashboard',
      cwd: '/home/ubuntu/garuda/apps/dashboard',
      script: 'node_modules/.bin/vite',
      args: 'preview --host --port 8080',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production' },
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 5000,
      max_memory_restart: '300M',
      time: true,
      error_file: '/root/.pm2/logs/dashboard-error.log',
      out_file: '/root/.pm2/logs/dashboard-out.log',
    },
    {
      // P-PWA.19: apps/pwa (chat publik) di port 8081 (bebeas — lihat audit P-PWA.18 poin 6).
      // Diikuti pola dashboard: vite preview --host, fork mode.
      name: 'pwa',
      cwd: '/home/ubuntu/garuda/apps/pwa',
      script: 'node_modules/.bin/vite',
      args: 'preview --host --port 8081',
      instances: 1,
      exec_mode: 'fork',
      env: { NODE_ENV: 'production' },
      kill_timeout: 10000,
      max_restarts: 5,
      min_uptime: 5000,
      max_memory_restart: '300M',
      time: true,
      error_file: '/root/.pm2/logs/pwa-error.log',
      out_file: '/root/.pm2/logs/pwa-out.log',
    },
  ],
};
