export const ErrorCodes = {
  // Internal
  ERR_INTERNAL: 'ERR_INTERNAL',
  ERR_INTERNAL_UNEXPECTED: 'ERR_INTERNAL_UNEXPECTED',

  // Validation
  ERR_VALIDATION: 'ERR_VALIDATION',
  ERR_VALIDATION_REQUIRED: 'ERR_VALIDATION_REQUIRED',
  ERR_VALIDATION_INVALID_FORMAT: 'ERR_VALIDATION_INVALID_FORMAT',
  ERR_VALIDATION_OUT_OF_RANGE: 'ERR_VALIDATION_OUT_OF_RANGE',

  // Database
  ERR_DB: 'ERR_DB',
  ERR_DB_CONNECTION: 'ERR_DB_CONNECTION',
  ERR_DB_NOT_FOUND: 'ERR_DB_NOT_FOUND',
  ERR_DB_DUPLICATE: 'ERR_DB_DUPLICATE',
  ERR_DB_TIMEOUT: 'ERR_DB_TIMEOUT',

  // Authentication
  ERR_AUTH: 'ERR_AUTH',
  ERR_AUTH_TOKEN_MISSING: 'ERR_AUTH_TOKEN_MISSING',
  ERR_AUTH_TOKEN_INVALID: 'ERR_AUTH_TOKEN_INVALID',
  ERR_AUTH_TOKEN_EXPIRED: 'ERR_AUTH_TOKEN_EXPIRED',
  ERR_AUTH_TOKEN_REVOKED: 'ERR_AUTH_TOKEN_REVOKED',
  ERR_AUTH_CREDENTIALS: 'ERR_AUTH_CREDENTIALS',
  ERR_AUTH_FORBIDDEN: 'ERR_AUTH_FORBIDDEN',
  ERR_AUTH_ACCOUNT_SUSPENDED: 'ERR_AUTH_ACCOUNT_SUSPENDED',

  // Rate Limit
  ERR_RATELIMIT: 'ERR_RATELIMIT',

  // External
  ERR_EXTERNAL: 'ERR_EXTERNAL',
  ERR_EXTERNAL_TIMEOUT: 'ERR_EXTERNAL_TIMEOUT',

  // External Unavailable (dependency missing, service down)
  ERR_EXTERNAL_UNAVAILABLE: 'ERR_EXTERNAL_UNAVAILABLE',

  // Not Found
  ERR_NOT_FOUND: 'ERR_NOT_FOUND',

  // Conflict
  ERR_CONFLICT: 'ERR_CONFLICT',

  // Magic Paste (Phase 1.9.3)
  ERR_MAGIC_PASTE_PARSE: 'ERR_MAGIC_PASTE_PARSE',
  ERR_PRICE_INVALID: 'ERR_PRICE_INVALID',
  ERR_SKU_GENERATION_FAILED: 'ERR_SKU_GENERATION_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export const HttpStatusMap: Record<string, number> = {
  [ErrorCodes.ERR_VALIDATION]: 400,
  [ErrorCodes.ERR_VALIDATION_REQUIRED]: 400,
  [ErrorCodes.ERR_VALIDATION_INVALID_FORMAT]: 400,
  [ErrorCodes.ERR_VALIDATION_OUT_OF_RANGE]: 400,
  [ErrorCodes.ERR_AUTH_TOKEN_MISSING]: 401,
  [ErrorCodes.ERR_AUTH_TOKEN_INVALID]: 401,
  [ErrorCodes.ERR_AUTH_TOKEN_EXPIRED]: 401,
  [ErrorCodes.ERR_AUTH_TOKEN_REVOKED]: 401,
  [ErrorCodes.ERR_AUTH_CREDENTIALS]: 401,
  [ErrorCodes.ERR_AUTH_ACCOUNT_SUSPENDED]: 401,
  [ErrorCodes.ERR_AUTH_FORBIDDEN]: 403,
  [ErrorCodes.ERR_NOT_FOUND]: 404,
  [ErrorCodes.ERR_CONFLICT]: 409,
  [ErrorCodes.ERR_MAGIC_PASTE_PARSE]: 400,
  [ErrorCodes.ERR_PRICE_INVALID]: 400,
  [ErrorCodes.ERR_SKU_GENERATION_FAILED]: 400,
  [ErrorCodes.ERR_RATELIMIT]: 429,
  [ErrorCodes.ERR_EXTERNAL_UNAVAILABLE]: 503,
  [ErrorCodes.ERR_DB_CONNECTION]: 503,
  [ErrorCodes.ERR_EXTERNAL_TIMEOUT]: 504,
};
